{% set name = "SwiftPol" %}
{% set version = ".0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/matta-research-group/SwiftPol/archive/v{{ version }}.tar.gz
  sha256: 3c3c48ce57bbd8458593d3a2994a4c502f4d18083c51eacde7d286653a41fe6a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - versioningit >=2.0,<3.dev0
    - pip
  run:
    - python >=3.7

test:
  imports:
    - swiftpol
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Tools for polymer molecular dynamics simulations.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hannaomi
